services:
  - type: web
    name: email-writer-ai
    rootDir: backend
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/*.jar
    envVars:
      - key: GEMINI_KEY
        sync: false
      - key: GEMINI_URL
        value: https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent
      - key: PORT
        value: 8080
